#!/usr/bin/env python3
"""Generate tests/fixtures/emitc_corpus/math/math_decimal.z and its golden.

math's fixed decimals -- decimal32, decimal64, decimal128, decimal256 -- at
several (precision, scale) instances each, against Python's exact integers on
the coefficients: + and - exact, * and / rounded half-even back to the scale,
overflow (|c| >= 10^precision) and division by zero invalid. Every operator's
results over every pair of a value table fold into one digest per instance:
an invalid result folds its reason, a valid one its coefficient (an i64's bits,
or a fixed int's hash -- FNV-1a over its words, which Python repeats). Text,
parse, fromRat in every rounding mode, the order, the conversions and the
sticky invalid paths are checked value by value.
"""
import os
import subprocess
import sys
from fractions import Fraction

# the repository: the first argument, else the tree this script is in
ROOT = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
M64 = (1 << 64) - 1
FNV_OFF = 14695981039346656037
FNV_PRIME = 1099511628211

# tier: (type, max digits, coefficient words for the hash, or 0 for an i64)
TIERS = {
    'decimal32': (9, 0),
    'decimal64': (18, 0),
    'decimal128': (38, 2),
    'decimal256': (76, 4),
}
INSTANCES = [
    ('decimal32', 9, 2), ('decimal32', 5, 0), ('decimal32', 4, 4),
    ('decimal64', 18, 2), ('decimal64', 10, 4), ('decimal64', 18, 0),
    ('decimal128', 38, 10), ('decimal128', 20, 5),
    ('decimal256', 76, 30), ('decimal256', 40, 0),
]


def fnv(h, w):
    return ((h ^ w) * FNV_PRIME) & M64


def lcg(seed, k):
    x = seed
    out = []
    for _ in range(k):
        x = (x * 6364136223846793005 + 1442695040888963407) & M64
        out.append(x)
    return out


def half_even_div(n, d):
    """n / d rounded to the nearest integer, ties to even (d != 0)."""
    q, r = divmod(abs(n), abs(d))
    twice = 2 * r
    if twice > abs(d) or (twice == abs(d) and q % 2 == 1):
        q += 1
    return q if (n < 0) == (d < 0) else -q


def coef_hash(c, words):
    if words == 0:
        return c % (1 << 64)
    h = FNV_OFF
    v = c % (1 << (64 * words))
    for i in range(words):
        h = fnv(h, (v >> (64 * i)) & M64)
    return h


INVALID_OVER = 0xD0
INVALID_DIV0 = 0xD1


def result_fold(r, words):
    if r == 'over':
        return INVALID_OVER
    if r == 'div0':
        return INVALID_DIV0
    return coef_hash(r, words)


def op(o, a, b, p, s):
    lim = 10 ** p
    if o == '+':
        c = a + b
    elif o == '-':
        c = a - b
    elif o == '*':
        c = half_even_div(a * b, 10 ** s)
    elif o == '/':
        if b == 0:
            return 'div0'
        c = half_even_div(a * 10 ** s, b)
    return 'over' if abs(c) >= lim else c


def text(c, s):
    neg = c < 0
    d = str(abs(c))
    if s > 0:
        d = d.rjust(s + 1, '0')
        d = d[:-s] + '.' + d[-s:]
    return ('-' if neg else '') + d


def values(p, s, seed):
    lim = 10 ** p
    vs = [0, 1, -1, lim - 1, -(lim - 1), 2, 7, -13]
    if s > 0:
        vs += [10 ** s, 5 * 10 ** (s - 1), -(10 ** s), 15 * 10 ** (s - 1)]
    if p > s:
        vs += [10 ** (p - 1), (lim // 2)]
    for x in lcg(seed, 6):
        v = x % lim
        vs.append(v if x & 1 else -v)
    for x in lcg(seed + 7, 4):
        v = x % (10 ** max(1, (p + 1) // 2))
        vs.append(v if x & 2 else -v)
    out = []
    for v in vs:
        if abs(v) < lim and v not in out:
            out.append(v)
    return out


MODES = ['toNearestEven', 'toNearestAway', 'toZero', 'awayFromZero', 'toNegativeInf', 'toPositiveInf']


def round_mode(fr, mode):
    n, d = fr.numerator, fr.denominator
    q, r = divmod(n, d)  # floor
    if r == 0:
        return q
    lo, hi = q, q + 1
    if mode == 'toNegativeInf':
        return lo
    if mode == 'toPositiveInf':
        return hi
    if mode == 'toZero':
        return lo if n > 0 else hi
    if mode == 'awayFromZero':
        return hi if n > 0 else lo
    twice = 2 * r
    if twice < d:
        return lo
    if twice > d:
        return hi
    if mode == 'toNearestAway':
        return hi if n > 0 else lo
    return lo if lo % 2 == 0 else hi


def gen():
    out = []
    w = out.append
    w('''# math_decimal.z -- math's fixed decimals at several (precision, scale) each,
# against Python's exact integers on the coefficients: + and - exact, * and /
# rounded half-even to the scale, overflow and division by zero invalid. Each
# operator's results over every pair of a value table fold into one digest per
# instance (an invalid one its reason, a valid one its coefficient); text,
# parse, fromRat in every rounding mode, the order, the conversions and the
# sticky invalid paths are checked value by value. Generated by
# decimaltables.py.

# the failures, and the checks run
Tally: class {
    checks: u64
    bad: u64
}

# big -- a BigInt from decimal text the test spells correctly
big: function {text: StringView} out math.BigInt is {
    r: math.BigInt.parse :text base: 10
    match r case ok then return r.take case err then panic msg: "bad test text"
}

# fold -- the FNV-1a step every digest takes
fold: function {d: u64 h: u64} out u64 is {
    return ((d ^ h).mulWide rhs: 1099511628211).lo
}

# digest -- one check: a digest against the oracle's
digest: function {t: Tally.borrow what: StringView got: u64 want: u64} is {
    t.checks = t.checks + 1
    if got != want then {
        t.bad = t.bad + 1
        print "FAIL \\{what}: digest \\{got}, want \\{want}"
    }
}

# same -- one check: the two texts agree
same: function {t: Tally.borrow what: StringView got: String.view want: StringView} is {
    t.checks = t.checks + 1
    if got != want then {
        t.bad = t.bad + 1
        print "FAIL \\{what}: \\{got}, want \\{want}"
    }
}

# truth -- one check: the condition holds
truth: function {t: Tally.borrow what: StringView ok: bool} is {
    t.checks = t.checks + 1
    if ok.not then {
        t.bad = t.bad + 1
        print "FAIL \\{what}"
    }
}
''')
    funcs = []
    for idx, (ty, p, s) in enumerate(INSTANCES):
        maxd, words = TIERS[ty]
        T = f'(math.{ty} precision: {p} scale: {s})'
        fname = f'{ty}_{p}_{s}'
        funcs.append(fname)
        vs = values(p, s, 0x9E3779B97F4A7C15 + idx * 31)
        fold_expr = 'r.coef.bits' if words == 0 and ty == 'decimal64' else (
            'r.coef.i64.bits' if words == 0 else 'r.coef.hash')
        dig = {}
        for o in '+-*/':
            d = FNV_OFF
            for a in vs:
                for b in vs:
                    d = fnv(d, result_fold(op(o, a, b, p, s), words))
            dig[o] = d
        dcmp = FNV_OFF
        for a in vs:
            for b in vs:
                dcmp = fnv(dcmp, ((a > b) - (a < b)) % (1 << 64))
        w(f'''
# {fname} -- {T}: {len(vs)} values
{fname}: function {{t: Tally.borrow}} is {{
    vs: ListVal {T}''')
        for v in vs:
            w(f'    vs.append from: ({T}.parse text: "{text(v, s)}").orPanic')
        w('''    dAdd: 14695981039346656037.u64
    dSub: dAdd
    dMul: dAdd
    dDiv: dAdd
    dCmp: dAdd
    for each a: vs loop {
        for each b: vs loop {''')
        for o, var in (('+', 'dAdd'), ('-', 'dSub'), ('*', 'dMul'), ('/', 'dDiv')):
            w(f'''            {{
                r: a {o} b
                rc: r.checked
                match rc case ok then {var} = fold d: {var} h: {fold_expr} case err then {{
                    match rc case overflow then {var} = fold d: {var} h: {INVALID_OVER} case divisionByZero then {var} = fold d: {var} h: {INVALID_DIV0}
                }}
            }}''')
        w('''            dCmp = fold d: dCmp h: (a.compare rhs: b).i64.bits
        }''')
        w(f'''        truth :t what: "{fname} text round trip" ok: ({T}.parse text: a.string.stringView).orPanic == a
        truth :t what: "{fname} rat round trip" ok: ({T}.fromRat from: a.rat mode: math.roundingmode.toZero) == a
    }}''')
        for o, var in (('+', 'dAdd'), ('-', 'dSub'), ('*', 'dMul'), ('/', 'dDiv')):
            w(f'    digest :t what: "{fname} {o}" got: {var} want: {dig[o]}')
        w(f'    digest :t what: "{fname} compare" got: dCmp want: {dcmp}')
        # explicit text, parse rounding and fromRat
        lim = 10 ** p
        hi = lim - 1
        w(f'    same :t what: "{fname} max" got: ({T}.fromCoef from: {coef_arg(ty, hi)}).string want: "{text(hi, s)}"')
        w(f'    same :t what: "{fname} -max" got: ({T}.fromCoef from: {coef_arg(ty, -hi)}).string want: "{text(-hi, s)}"')
        w(f'    truth :t what: "{fname} max+1 invalid" ok: (({T}.fromCoef from: {coef_arg(ty, hi)}) + ({T}.fromCoef from: {coef_arg(ty, 1)})).isInvalid')
        w(f'    same :t what: "{fname} invalid text" got: (({T}.fromCoef from: {coef_arg(ty, hi)}) + ({T}.fromCoef from: {coef_arg(ty, 1)})).string want: "invalid"')
        w(f'    zero: {T} from: 0')
        w(f'    one: {T}.fromCoef from: {coef_arg(ty, 1)}')
        w(f'    div0: one / zero')
        w(f'    truth :t what: "{fname} x/0 invalid" ok: div0.isInvalid')
        w(f'    truth :t what: "{fname} invalid is sticky" ok: ((div0 + one).isInvalid) and ((one * div0).isInvalid) and ((div0 - div0).isInvalid)')
        w(f'    truth :t what: "{fname} invalid == invalid" ok: (div0 == (one / zero)) and (div0 != one) and (div0.hash == (one / zero).hash)')
        w(f'    rc0: div0.checked')
        w(f'    match rc0 case ok then truth :t what: "{fname} /0 reason" ok: false case err then {{')
        w(f'        match rc0 case divisionByZero then truth :t what: "{fname} /0 reason" ok: true case overflow then truth :t what: "{fname} /0 reason" ok: false')
        w('    }')
        w(f'    dflt: {T}')
        w(f'    truth :t what: "{fname} zero is default" ok: dflt == zero')
        # parse rounding at the scale
        tie = '0.' + '0' * s + '5' if s > 0 else '0.5'
        tie_want = 0
        w(f'    same :t what: "{fname} parse half to even" got: ({T}.parse text: "{tie}").orPanic.string want: "{text(tie_want, s)}"')
        tie2 = text(1, s) + '5' if s > 0 else '1.5'
        tie2_want = 2
        w(f'    same :t what: "{fname} parse half up to even" got: ({T}.parse text: "{tie2}").orPanic.string want: "{text(tie2_want, s)}"')
        w(f'    over: {T}.parse text: "{text(hi, s)}9"')
        if s == 0:
            w(f'    match over case ok then truth :t what: "{fname} parse overflow" ok: false case err then truth :t what: "{fname} parse overflow" ok: true')
        else:
            # a ninth digit past the scale rounds the max up to overflow
            w(f'    match over case ok then truth :t what: "{fname} parse overflow" ok: false case err then truth :t what: "{fname} parse overflow" ok: true')
        w(f'    bad: {T}.parse text: "1.2x"')
        w(f'    match bad case ok then truth :t what: "{fname} parse bad" ok: false case err then truth :t what: "{fname} parse bad" ok: true')
        # fromRat in every mode on -7/3 and 5/2 (scaled)
        for num, den in ((-7, 3), (5, 2), (2, 3), (-5, 2)):
            fr = Fraction(num, den) / (10 ** s) * 1 if False else Fraction(num, den)
            for mode in MODES:
                c = round_mode(fr * (10 ** s), mode)
                want = 'invalid' if abs(c) >= lim else text(c, s)
                w(f'    same :t what: "{fname} fromRat {num}/{den} {mode}" got: ({T}.fromRat from: (math.BigRat.fromFraction num: (math.BigInt from: {num}) den: (math.BigInt from: {den})) mode: math.roundingmode.{mode}).string want: "{want}"')
        w('}')
    w('''
main: function is {
    t: Tally checks: 0 bad: 0''')
    for f in funcs:
        w(f'    {f} :t')
    w('''    if t.bad == 0 then {
        print "ok \\{t.checks} checks"
    } else {
        print "\\{t.bad} of \\{t.checks} checks FAILED"
    }
}''')
    return '\n'.join(out) + '\n'


def coef_arg(ty, v):
    if ty in ('decimal32', 'decimal64'):
        return str(v)
    return f'(big text: "{v}")'


src = gen()
dst = f'{ROOT}/tests/fixtures/emitc_corpus/math/math_decimal.z' if len(sys.argv) < 3 else sys.argv[2]
open(dst, 'w').write(src)
subprocess.run([f'{ROOT}/bin/zl', 'fmt', dst], check=False, stdout=subprocess.DEVNULL)
print('wrote', dst, src.count('\n'), 'lines')
