#!/usr/bin/env python3
"""Generate tests/fixtures/emitc_corpus/math/math_fixedfloat.z and its golden.

math's fixed binary floats, (float words: N), against Python's exact rationals
rounded once to 64N mantissa bits, ties to even: every operator over every
pair of a value table, and the square root of each, fold into one digest per
operator and width -- the sign, the form, the exponent and the mantissa's words
(0.5 <= mantissa < 1), which the test reads from the value's own fields.
"""
import os
import subprocess
import sys
from fractions import Fraction
from math import isqrt

# the repository: the first argument, else the tree this script is in
ROOT = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
M64 = (1 << 64) - 1
FNV_OFF = 14695981039346656037
FNV_PRIME = 1099511628211
WIDTHS = [1, 2, 4]
TEXTS = ['0', '1', '-1', '3', '0.1', '-2.5', '1e300', '-1e-300', '123456789012345678901234567890',
         '0.3333333333333333333333333333333333333333333333333333333', '18446744073709551617',
         '-7.25e-20', '1e-5000', '6.02214076e23']


def fnv(h, w):
    return ((h ^ w) * FNV_PRIME) & M64


def round_to(x, prec, sticky=False):
    """x (a Fraction, nonzero) rounded to prec bits, ties to even: (neg, exp,
    m) with x ~ m * 2^(exp - prec), 2^(prec-1) <= m < 2^prec. `sticky` says the
    true value lies just above |x| (an inexact square root)."""
    neg = x < 0
    a = -x if neg else x
    e = a.numerator.bit_length() - a.denominator.bit_length()
    if Fraction(2) ** e > a:
        e -= 1
    # 2^e <= a < 2^(e+1); the mantissa's binary point sits above bit e
    exp = e + 1
    q = a * Fraction(2) ** (prec - exp)
    m = q.numerator // q.denominator
    rem = q - m
    half = Fraction(1, 2)
    if rem > half or (rem == half and (sticky or m % 2 == 1)) or (rem == half and sticky):
        m += 1
    if m == 1 << prec:
        m >>= 1
        exp += 1
    return neg, exp, m


def fold_value(d, x, n, sticky=False):
    """fold a rounded value as the test folds a float's fields"""
    if x == 0:
        return fnv(fnv(fnv(d, 0), 0), 0)
    neg, exp, m = round_to(x, 64 * n, sticky)
    d = fnv(d, 1 if neg else 0)
    d = fnv(d, 1)
    d = fnv(d, exp % (1 << 64))
    for i in range(n):
        d = fnv(d, (m >> (64 * i)) & M64)
    return d


def rounded(x, n):
    if x == 0:
        return Fraction(0)
    neg, exp, m = round_to(x, 64 * n)
    v = Fraction(m) * Fraction(2) ** (exp - 64 * n)
    return -v if neg else v


def sqrt_fold(d, v, n):
    """fold the rounded square root of v (v >= 0)"""
    if v == 0:
        return fold_value(d, Fraction(0), n)
    prec = 64 * n
    # scale v by 4^t so its integer part carries far more than prec bits
    t = prec + 64 - (v.numerator.bit_length() - v.denominator.bit_length()) // 2
    scaled = v * Fraction(4) ** t
    whole = scaled.numerator // scaled.denominator
    r = isqrt(whole)
    exact = r * r == whole and scaled.denominator == 1
    root = Fraction(r) / Fraction(2) ** t
    if exact:
        return fold_value(d, root, n)
    # inexact: the true root lies strictly between r and r+1 at that scale, so
    # it rounds as r plus a sticky half-bit far below the mantissa
    return fold_value(d, root + Fraction(1) / Fraction(2) ** (t + 1), n, sticky=True)


def gen():
    out = []
    w = out.append
    w('''# math_fixedfloat.z -- math's fixed binary floats, (float words: N), against
# Python's exact rationals rounded once to 64N mantissa bits, ties to even.
# Every operator over every pair of a value table, and each value's square root,
# fold into one digest per operator and width: the sign, the form, the exponent
# and the mantissa's words, read from the value's own fields. Generated by
# fixedfloattables.py.

# the failures, and the checks run
Tally: class {
    checks: u64
    bad: u64
}

# fold -- the FNV-1a step every digest takes
fold: function {d: u64 h: u64} out u64 is {
    return ((d ^ h).mulWide rhs: 1099511628211).lo
}

# digest -- one check: a digest against the oracle's
digest: function {t: Tally.borrow what: StringView got: u64 want: u64} is {
    t.checks = t.checks + 1
    if got != want then {
        t.bad = t.bad + 1
        print "FAIL \\{what}: digest \\{got}, want \\{want}"
    }
}

# truth -- one check: the condition holds
truth: function {t: Tally.borrow what: StringView ok: bool} is {
    t.checks = t.checks + 1
    if ok.not then {
        t.bad = t.bad + 1
        print "FAIL \\{what}"
    }
}
''')
    funcs = []
    for n in WIDTHS:
        T = f'(math.float words: {n})'
        fname = f'float{n}'
        funcs.append(fname)
        vals = [rounded(Fraction(tx), n) for tx in TEXTS]
        w(f'''
# fields{n} -- a {T}'s fields folded into d
fields{n}: function {{d: u64 x: {T}.view}} out u64 is {{
    r: d
    s: 0.u64
    if x.negative then s = 1
    f: 0.u64
    if x.form.finite then f = 1
    if x.form.inf then f = 2
    if x.form.zero then {{
        r = fold d: r h: 0
        r = fold d: r h: 0
        return (fold d: r h: 0)
    }}
    r = fold d: r h: s
    r = fold d: r h: f
    r = fold d: r h: x.exp.i64.bits
    i: u64
    for i < {n} loop {{
        r = fold d: r h: (x.mant.get :i)
        i = i + 1
    }}
    return r
}}

# {fname} -- {T}: {len(TEXTS)} values
{fname}: function {{t: Tally.borrow}} is {{
    vs: ListVal {T}''')
        for tx in TEXTS:
            w(f'    vs.append from: ({T}.parse text: "{tx}").orPanic')
        dig = {}
        for o in '+-*/':
            d = FNV_OFF
            for a in vals:
                for b in vals:
                    if o == '/' and b == 0:
                        continue
                    r = {'+': a + b, '-': a - b, '*': a * b, '/': (a / b) if b != 0 else None}[o]
                    d = fold_value(d, r, n)
            dig[o] = d
        dparse = FNV_OFF
        for v in vals:
            dparse = fold_value(dparse, v, n)
        dsqrt = FNV_OFF
        for v in vals:
            if v >= 0:
                dsqrt = sqrt_fold(dsqrt, v, n)
        dcmp = FNV_OFF
        for a in vals:
            for b in vals:
                dcmp = fnv(dcmp, ((a > b) - (a < b)) % (1 << 64))
        w('''    dParse: 14695981039346656037.u64
    dAdd: dParse
    dSub: dParse
    dMul: dParse
    dDiv: dParse
    dSqrt: dParse
    dCmp: dParse
    for each a: vs loop {''')
        w(f'''        dParse = fields{n} d: dParse x: a
        if a.sign >= 0 then dSqrt = fields{n} d: dSqrt x: a.sqrt
        for each b: vs loop {{
            dAdd = fields{n} d: dAdd x: a + b
            dSub = fields{n} d: dSub x: a - b
            dMul = fields{n} d: dMul x: a * b
            if b.sign != 0 then dDiv = fields{n} d: dDiv x: a / b
            dCmp = fold d: dCmp h: (a.compare rhs: b).i64.bits
        }}
        truth :t what: "{fname} big round trip" ok: ({T}.fromBig from: a.big) == a
        truth :t what: "{fname} neg neg" ok: a.neg.neg == a
    }}''')
        w(f'    digest :t what: "{fname} parse" got: dParse want: {dparse}')
        for o, var in (('+', 'dAdd'), ('-', 'dSub'), ('*', 'dMul'), ('/', 'dDiv')):
            w(f'    digest :t what: "{fname} {o}" got: {var} want: {dig[o]}')
        w(f'    digest :t what: "{fname} sqrt" got: dSqrt want: {dsqrt}')
        w(f'    digest :t what: "{fname} compare" got: dCmp want: {dcmp}')
        w(f'''    inf: {T}.inf negative: false
    one: {T} from: 1.0
    truth :t what: "{fname} inf + 1" ok: (inf + one).isInf and ((inf + one).sign == 1)
    truth :t what: "{fname} 1 / inf" ok: (one / inf).sign == 0
    truth :t what: "{fname} -0 == 0" ok: (one - one).neg == ({T} from: 0.0)
    truth :t what: "{fname} f64 exact" ok: ({T} from: 0.1).roundF64 == 0.1
    third: math.BigRat.fromFraction num: (math.BigInt from: 1) den: (math.BigInt from: 3)
    truth :t what: "{fname} fromBig rounds a wider float" ok: ({T}.fromBig from: (math.BigFloat.fromRat from: third prec: 1000)) == ({T}.fromRat from: third)
    truth :t what: "{fname} fromBig rounds to nearest" ok: ({T}.fromBig from: (math.BigFloat.fromRat from: third.neg prec: 1000)) == ({T}.fromRat from: third.neg)
    dflt: {T}
    truth :t what: "{fname} zero is default" ok: dflt == ({T} from: 0.0)
}}''')
    w('''
main: function is {
    t: Tally checks: 0 bad: 0''')
    for f in funcs:
        w(f'    {f} :t')
    w('''    if t.bad == 0 then {
        print "ok \\{t.checks} checks"
    } else {
        print "\\{t.bad} of \\{t.checks} checks FAILED"
    }
}''')
    return '\n'.join(out) + '\n'


src = gen()
dst = f'{ROOT}/tests/fixtures/emitc_corpus/math/math_fixedfloat.z' if len(sys.argv) < 3 else sys.argv[2]
open(dst, 'w').write(src)
subprocess.run([f'{ROOT}/bin/zl', 'fmt', dst], check=False, stdout=subprocess.DEVNULL)
print('wrote', dst, src.count('\n'), 'lines')
