#!/usr/bin/env python3
"""Generate tests/fixtures/emitc_corpus/math/math_fixedint.z and its golden.

math's fixed-width integers, (int words: N) and (uint words: N), cross-checked
against Python's ints reduced mod 2^(64N). For each width and signedness a
table of edge and pseudo-random values is built from text; every binary
operator runs over every pair, the shifts over a set of counts, the unary ones
over every value, and each operator's results are folded into one digest
through the type's own `hash` (FNV-1a over the words, which Python repeats).
A failing digest names its operator and width. Text, conversions and the
BigInt round trip are checked value by value.
"""
import os
import subprocess
import sys

# the repository: the first argument, else the tree this script is in
ROOT = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
M64 = (1 << 64) - 1
WIDTHS = [1, 2, 3, 4, 8]
FNV_OFF = 14695981039346656037
FNV_PRIME = 1099511628211


def lcg(seed, k):
    x = seed
    out = []
    for _ in range(k):
        x = (x * 6364136223846793005 + 1442695040888963407) & M64
        out.append(x)
    return out


def fnv(h, w):
    return ((h ^ w) * FNV_PRIME) & M64


def limbs(v, n):
    v %= 1 << (64 * n)
    return [(v >> (64 * i)) & M64 for i in range(n)]


def whash(v, n):
    h = FNV_OFF
    for w in limbs(v, n):
        h = fnv(h, w)
    return h


def signed(v, n):
    v %= 1 << (64 * n)
    if v >> (64 * n - 1):
        v -= 1 << (64 * n)
    return v


def values(n, sgn):
    w = 64 * n
    vs = [0, 1, 2, 3, (1 << 63), M64, (1 << 64), (1 << w) - 1, (1 << w) - 2, (1 << (w - 1)),
          (1 << (w - 1)) - 1, 12345678901234567890 % (1 << w)]
    r = lcg(0x9E3779B97F4A7C15 + n + (100 if sgn else 0), 4 * n)
    for i in range(4):
        vs.append(sum(x << (64 * j) for j, x in enumerate(r[i * n:(i + 1) * n])))
    out = []
    for v in vs:
        v %= 1 << w
        if sgn:
            v = signed(v, n)
        if v not in out:
            out.append(v)
    return out


def tdiv(a, b):
    q = abs(a) // abs(b)
    return q if (a < 0) == (b < 0) else -q


def binop(op, a, b, n, sgn):
    w = 64 * n
    if op == '+':
        r = a + b
    elif op == '-':
        r = a - b
    elif op == '*':
        r = a * b
    elif op == '/':
        r = tdiv(a, b) if sgn else a // b
    elif op == '%':
        r = a - b * tdiv(a, b) if sgn else a % b
    elif op == '&':
        r = (a % (1 << w)) & (b % (1 << w))
    elif op == '|':
        r = (a % (1 << w)) | (b % (1 << w))
    elif op == '^':
        r = (a % (1 << w)) ^ (b % (1 << w))
    return r % (1 << w)


OPS = ['+', '-', '*', '/', '%', '&', '|', '^']
OPNAME = {'+': 'add', '-': 'sub', '*': 'mul', '/': 'div', '%': 'rem', '&': 'and', '|': 'or', '^': 'xor'}


def gen():
    out = []
    w = out.append
    w('''# math_fixedint.z -- math's fixed-width integers, (int words: N) and (uint words:
# N), against Python's ints reduced mod 2^(64N). For each width and signedness
# a table of edge and pseudo-random values is read from text; each operator's
# results over every pair (the shifts over a set of counts, the unary ones over
# every value) fold into one digest through the type's own `hash`, so a failing
# digest names its operator and width. Text, conversions and the BigInt round
# trip are checked value by value. Generated by fixedtables.py.

# the failures, and the checks run
Tally: class {
    checks: u64
    bad: u64
}

# fold -- the FNV-1a step every digest takes, over a hash
fold: function {d: u64 h: u64} out u64 is {
    return ((d ^ h).mulWide rhs: 1099511628211).lo
}

# digest -- one check: a digest against the oracle's
digest: function {t: Tally.borrow what: StringView got: u64 want: u64} is {
    t.checks = t.checks + 1
    if got != want then {
        t.bad = t.bad + 1
        print "FAIL \\{what}: digest \\{got}, want \\{want}"
    }
}

# same -- one check: the two texts agree
same: function {t: Tally.borrow what: StringView got: String.view want: StringView} is {
    t.checks = t.checks + 1
    if got != want then {
        t.bad = t.bad + 1
        print "FAIL \\{what}: \\{got}, want \\{want}"
    }
}

# truth -- one check: the condition holds
truth: function {t: Tally.borrow what: StringView ok: bool} is {
    t.checks = t.checks + 1
    if ok.not then {
        t.bad = t.bad + 1
        print "FAIL \\{what}"
    }
}
''')
    funcs = []
    for n in WIDTHS:
        for sgn in (True, False):
            kind = 'int' if sgn else 'uint'
            T = f'(math.{kind} words: {n})'
            fname = f'{kind}{n}'
            funcs.append(fname)
            vs = values(n, sgn)
            W = 64 * n
            shifts = sorted(set([0, 1, 63, 64, 65, W - 1, W, W + 5]))
            # oracle digests
            dig = {}
            for op in OPS:
                d = FNV_OFF
                for a in vs:
                    for b in vs:
                        if op in '/%' and b == 0:
                            continue
                        d = fnv(d, whash(binop(op, a, b, n, sgn), n))
                dig[op] = d
            dcmp = FNV_OFF
            for a in vs:
                for b in vs:
                    c = (a > b) - (a < b)
                    dcmp = fnv(dcmp, c % (1 << 64))
            dshl = FNV_OFF
            dshr = FNV_OFF
            for a in vs:
                for s in shifts:
                    dshl = fnv(dshl, whash((a << s) % (1 << W), n))
                    if sgn:
                        r = a >> s
                    else:
                        r = (a % (1 << W)) >> s
                    dshr = fnv(dshr, whash(r % (1 << W), n))
            dnot = FNV_OFF
            dneg = FNV_OFF
            for a in vs:
                dnot = fnv(dnot, whash(~a % (1 << W), n))
                dneg = fnv(dneg, whash(-a % (1 << W), n))
            di64 = FNV_OFF
            du64 = FNV_OFF
            for a in vs:
                di64 = fnv(di64, (a % (1 << 64)) if -(1 << 63) <= a < (1 << 63) else 0x5A5A)
                du64 = fnv(du64, a if 0 <= a <= M64 else 0x5A5A)
            w(f'''
# {fname} -- {T}: {len(vs)} values
{fname}: function {{t: Tally.borrow}} is {{
    vs: ListVal {T}''')
            for v in vs:
                w(f'    vs.append from: ({T}.parse text: "{v}" base: 10).orPanic')
            w(f'    zero: {T} from: 0')
            w('''    dAdd: 14695981039346656037.u64
    dSub: dAdd
    dMul: dAdd
    dDiv: dAdd
    dRem: dAdd
    dAnd: dAdd
    dOr: dAdd
    dXor: dAdd
    dCmp: dAdd
    for each a: vs loop {
        for each b: vs loop {
            dAdd = fold d: dAdd h: (a + b).hash
            dSub = fold d: dSub h: (a - b).hash
            dMul = fold d: dMul h: (a * b).hash
            dAnd = fold d: dAnd h: (a & b).hash
            dOr = fold d: dOr h: (a | b).hash
            dXor = fold d: dXor h: (a ^ b).hash
            dCmp = fold d: dCmp h: (a.compare rhs: b).i64.bits
            if b != zero then {
                dDiv = fold d: dDiv h: (a / b).hash
                dRem = fold d: dRem h: (a % b).hash
            }
        }
    }''')
            for op in OPS:
                var = 'd' + OPNAME[op].capitalize()
                w(f'    digest :t what: "{fname} {OPNAME[op]}" got: {var} want: {dig[op]}')
            w(f'    digest :t what: "{fname} compare" got: dCmp want: {dcmp}')
            w(f'''    dShl: 14695981039346656037.u64
    dShr: dShl
    dNot: dShl
    dNeg: dShl
    dI64: dShl
    dU64: dShl
    for each a: vs loop {{''')
            for s in shifts:
                w(f'        dShl = fold d: dShl h: (a << {s}).hash')
                w(f'        dShr = fold d: dShr h: (a >> {s}).hash')
            w('''        dNot = fold d: dNot h: a.not.hash
        dNeg = fold d: dNeg h: (zero - a).hash
        ri: a.i64
        match ri case ok then dI64 = fold d: dI64 h: ri.bits case err then dI64 = fold d: dI64 h: 23130
        ru: a.u64
        match ru case ok then dU64 = fold d: dU64 h: ru case err then dU64 = fold d: dU64 h: 23130''')
            w(f'''        truth :t what: "{fname} big round trip" ok: ({T}.fromBig from: a.big).orPanic == a
        truth :t what: "{fname} text round trip" ok: ({T}.parse text: a.string.stringView base: 10).orPanic == a
        truth :t what: "{fname} hex round trip" ok: ({T}.parse text: (a.text base: 16).stringView base: 16).orPanic == a
    }}''')
            w(f'    digest :t what: "{fname} shl" got: dShl want: {dshl}')
            w(f'    digest :t what: "{fname} shr" got: dShr want: {dshr}')
            w(f'    digest :t what: "{fname} not" got: dNot want: {dnot}')
            w(f'    digest :t what: "{fname} neg" got: dNeg want: {dneg}')
            w(f'    digest :t what: "{fname} i64" got: dI64 want: {di64}')
            w(f'    digest :t what: "{fname} u64" got: dU64 want: {du64}')
            # edges, by text
            lo = -(1 << (W - 1)) if sgn else 0
            hi = (1 << (W - 1)) - 1 if sgn else (1 << W) - 1
            w(f'    same :t what: "{fname} max" got: ({T}.parse text: "{hi}" base: 10).orPanic.string want: "{hi}"')
            w(f'    same :t what: "{fname} min" got: ({T}.parse text: "{lo}" base: 10).orPanic.string want: "{lo}"')
            w(f'    same :t what: "{fname} max+1 wraps" got: (({T}.parse text: "{hi}" base: 10).orPanic + ({T} from: 1)).string want: "{lo}"')
            w(f'    same :t what: "{fname} min-1 wraps" got: (({T}.parse text: "{lo}" base: 10).orPanic - ({T} from: 1)).string want: "{hi}"')
            w(f'    over: {T}.parse text: "{hi + 1}" base: 10')
            w(f'    match over case ok then truth :t what: "{fname} max+1 refused" ok: false case err then truth :t what: "{fname} max+1 refused" ok: true')
            w(f'    under: {T}.parse text: "{lo - 1}" base: 10')
            w(f'    match under case ok then truth :t what: "{fname} min-1 refused" ok: false case err then truth :t what: "{fname} min-1 refused" ok: true')
            w(f'    dflt: {T}')
            w(f'    truth :t what: "{fname} zero is default" ok: dflt == zero')
            if sgn:
                w(f'    same :t what: "{fname} min/-1" got: (({T}.parse text: "{lo}" base: 10).orPanic / ({T} from: -1)).string want: "{lo}"')
                w(f'    same :t what: "{fname} min%-1" got: (({T}.parse text: "{lo}" base: 10).orPanic % ({T} from: -1)).string want: "0"')
                w(f'    same :t what: "{fname} -7/2" got: (({T} from: -7) / ({T} from: 2)).string want: "-3"')
                w(f'    same :t what: "{fname} -7%2" got: (({T} from: -7) % ({T} from: 2)).string want: "-1"')
                w(f'    same :t what: "{fname} -1 hex" got: (({T} from: -1).text base: 16) want: "-1"')
            w('}')
    w('''
main: function is {
    t: Tally checks: 0 bad: 0''')
    for f in funcs:
        w(f'    {f} :t')
    w('''    if t.bad == 0 then {
        print "ok \\{t.checks} checks"
    } else {
        print "\\{t.bad} of \\{t.checks} checks FAILED"
    }
}''')
    return '\n'.join(out) + '\n'


src = gen()
dst = f'{ROOT}/tests/fixtures/emitc_corpus/math/math_fixedint.z' if len(sys.argv) < 3 else sys.argv[2]
open(dst, 'w').write(src)
subprocess.run([f'{ROOT}/bin/zl', 'fmt', dst], check=False, stdout=subprocess.DEVNULL)
print('wrote', dst, src.count('\n'), 'lines')
