#!/usr/bin/env python3
"""Generate tests/fixtures/emitc_corpus/math/math_kernel_shapes.z and its golden.

The word-vector kernels (src/runtime/natives/_Z_MATH_ARITH.inc and the asm
fragments beside it) at the operand shapes they special-case: lengths 0 and 1,
a carry or borrow through every word, a carry that dies early (the copy of the
rest), shifts by 0/1/63 and by whole words, the in-place twins (BigInt's
add/sub/mul/quo/rem accumulate), every length 1 to 17 (either side of where the
asm kernels take over and every remainder of their unrolling), and sizes
either side of the karatsuba (48), divRecursive (40) and karatsubaSqr (80)
thresholds. Python's ints are the oracle. A result is compared
exactly while it is short, and by a digest (sign, bit length, trailing zeros,
the value mod a two-word prime) once it is long.
"""
import os
import subprocess
import sys

# the repository: the first argument, else the tree this script is in
ROOT = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SIZES = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 23, 24, 25, 39, 40, 41, 47, 48, 49, 59, 60, 61, 79, 80, 81, 100]
P = (1 << 127) - 1  # a Mersenne prime of two words
SHIFTS = [0, 1, 63, 64, 65, 127]


def lcg_words(k, seed):
    x = seed
    ws = []
    for _ in range(k):
        x = (x * 6364136223846793005 + 1442695040888963407) & ((1 << 64) - 1)
        ws.append(x)
    return sum(w << (64 * i) for i, w in enumerate(ws))


def hexs(v):
    return ('-' if v < 0 else '') + format(abs(v), 'x')


def tz(v):
    v = abs(v)
    if v == 0:
        return 0
    return (v & -v).bit_length() - 1


def digest(v):
    if abs(v).bit_length() <= 192:
        return hexs(v)
    s = (v > 0) - (v < 0)
    return f'{s} {abs(v).bit_length()} {tz(v)} {format(abs(v) % P, "x")}'


def trunc_div(a, b):
    q = abs(a) // abs(b)
    return q if (a < 0) == (b < 0) else -q


def trunc_rem(a, b):
    return a - b * trunc_div(a, b)


out = []
w = out.append
w('''# math_kernel_shapes.z -- BigInt through its word-vector kernels at the operand
# shapes they special-case: lengths 0 and 1, a carry or a borrow through every
# word, one that dies early (the rest is copied), shifts by 0, 1, 63 and whole
# words, the in-place twins (BigInt's add, sub, mul, quo and rem accumulate),
# every length 1 to 17 -- either side of where the asm kernels take over (4, 8,
# 9) and every remainder of their 4- and 8-word unrolling -- and sizes either
# side of the karatsuba (48), divRecursive (40) and Karatsuba squaring (80)
# thresholds, and at 23 to 25, 59 to 61 and 100 words. Generated by kerneltables.py,
# Python's ints the oracle; a long result is compared by its digest.

# the failures, and the checks run
Tally: class {
    checks: u64
    bad: u64
}

# big -- a BigInt from hexadecimal text the test spells correctly
big: function {text: StringView} out math.BigInt is {
    r: math.BigInt.parse :text base: 16
    match r case ok then return r.take case err then panic msg: "bad test text"
}

# digest -- x exactly while it fits three words, else its sign, bit length,
# trailing zeros and the residue of its magnitude mod p
digest: function {x: math.BigInt.view p: math.BigInt.view} out String is {
    if x.bitLength <= 192 then return (x.text base: 16)
    return "\\{x.sign} \\{x.bitLength} \\{x.trailingZeros} \\{(x.abs % p).text base: 16}"
}

# same -- one check: the digest of got is want
same: function {t: Tally.borrow what: StringView got: math.BigInt.view want: StringView p: math.BigInt.view} is {
    t.checks = t.checks + 1
    g: digest x: got :p
    if g != want then {
        t.bad = t.bad + 1
        print "FAIL \\{what}: \\{g}, want \\{want}"
    }
}
''')

for k in SIZES:
    n = 64 * k
    A = (1 << n) - 1
    B = 1 << n
    D = lcg_words(k, 0x9E3779B97F4A7C15 + k) | 1
    E = lcg_words(max(k // 2, 1), 0xD1B54A32D192ED03 + k) | (1 << 63)
    ONE = 1
    W = (1 << 64) - 1
    checks = []

    def c(what, expr, val):
        checks.append((what, expr, val))

    c('a+1', 'a + one', A + 1)
    c('1+a', 'one + a', 1 + A)
    c('b-1', 'b - one', B - 1)
    c('1-b', 'one - b', 1 - B)
    c('a+a', 'a + a', A + A)
    c('a-a', 'a - a', 0)
    c('a+d', 'a + d', A + D)
    c('d-a', 'd - a', D - A)
    c('d+w', 'd + w', D + W)
    c('d-w', 'd - w', D - W)
    c('a*w', 'a * w', A * W)
    c('d*w', 'd * w', D * W)
    c('a*a', 'a * a', A * A)
    c('a*d', 'a * d', A * D)
    c('d*d', 'd * d', D * D)
    c('d*e', 'd * e', D * E)
    for s in SHIFTS + [n, n + 1]:
        c(f'a<<{s}', f'a << {s}', A << s)
        c(f'd<<{s}', f'd << {s}', D << s)
        c(f'a>>{s}', f'a >> {s}', A >> s)
        c(f'd>>{s}', f'd >> {s}', D >> s)
        c(f'-d>>{s}', f'd.neg >> {s}', (-D) >> s)
    if D != 0:
        N = A * D + (D >> 1)
        c('(a*d+d/2)/d', '((a * d) + (d >> 1)) / d', trunc_div(N, D))
        c('(a*d+d/2)%d', '((a * d) + (d >> 1)) % d', trunc_rem(N, D))
        c('b/d', 'b / d', trunc_div(B, D))
        c('b%d', 'b % d', trunc_rem(B, D))
        c('-b/d', 'b.neg / d', trunc_div(-B, D))
        c('d*d/e', '(d * d) / e', trunc_div(D * D, E))
        c('d*d%e', '(d * d) % e', trunc_rem(D * D, E))
    if A != 0:
        c('b/a', 'b / a', trunc_div(B, A))
        c('b%a', 'b % a', trunc_rem(B, A))
        c('a*a/a', '(a * a) / a', A)
    # the accumulators: each step's operand is the running value's own
    # window in the in-place kernels
    acc = []
    x = A
    acc.append(('x.add one', 'x += 1', x + 1)); x = x + 1
    acc.append(('x.sub one', 'x -= 1', x - 1)); x = x - 1
    acc.append(('x.add d', 'x += d', x + D)); x = x + D
    acc.append(('x.sub a', 'x -= a', x - A)); x = x - A
    acc.append(('x.mul d', 'x *= d', x * D)); x = x * D
    acc.append(('x.add w', 'x += w', x + W)); x = x + W
    acc.append(('x.quo d', 'x /= d', trunc_div(x, D))); x = trunc_div(x, D)
    acc.append(('x.sub b', 'x -= b', x - B)); x = x - B
    acc.append(('x.rem e', 'x %= e', trunc_rem(x, E))); x = trunc_rem(x, E)

    w(f'''
# words{k} -- the shapes at {k} words: a all ones, b = a + 1, d and e
# pseudo-random (d odd, e half d's length with its top bit set)
words{k}: function {{t: Tally.borrow p: math.BigInt.view}} is {{
    one: math.BigInt from: 1
    w: big text: "ffffffffffffffff"
    a: big text: "{hexs(A)}"
    b: one << {n}
    d: big text: "{hexs(D)}"
    e: big text: "{hexs(E)}"''')
    for what, expr, val in checks:
        w(f'    same :t what: "{k}w {what}" got: ({expr}) want: "{digest(val)}" :p')
    w('    x: a.copy')
    for z, what, val in acc:
        meth, arg = z.split(' ')[0].split('.')[1], z.split(' ')[1]
        w(f'    x.{meth} x: {arg}')
        w(f'    same :t what: "{k}w {what}" got: x want: "{digest(val)}" :p')
    # BigFloat rounding a all-ones mantissa up: the carry runs through every
    # word of the mantissa (addVWInPlace)
    if k > 0:
        w(f'''    f: math.BigFloat.fromInt from: a prec: {n - 1}
    fi: f.truncInt
    match fi case some then {{
        same :t what: "{k}w round a to {n - 1} bits" got: fi want: "{digest(B)}" :p
    }} case none then {{
        same :t what: "{k}w round a to {n - 1} bits" got: one want: "inf" :p
    }}''')
    w('}')

w(f'''
main: function is {{
    t: Tally checks: 0 bad: 0
    p: big text: "{format(P, 'x')}"''')
for k in SIZES:
    w(f'    words{k} :t :p')
w('''    if t.bad == 0 then {
        print "ok \\{t.checks} checks"
    } else {
        print "\\{t.bad} of \\{t.checks} checks FAILED"
    }
}''')

src = '\n'.join(out) + '\n'
dst = f'{ROOT}/tests/fixtures/emitc_corpus/math/math_kernel_shapes.z'
open(dst, 'w').write(src)
subprocess.run([f'{ROOT}/bin/zl', 'fmt', dst], check=True, stdout=subprocess.DEVNULL)
total = src.count('\n    same :t') + src.count('\n        same :t') // 2
print('lines', src.count('\n'), 'checks', total)
