/* Generated by zerolang compiler */

#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

typedef struct {
    uint64_t size;     /* bits 62-0: byte count; bit 63: static flag */
    char data[];       /* NUL-terminated, starts at 8-byte boundary */
} ZStr;

#define ZSTR_STATIC_FLAG  0x8000000000000000ull
#define ZSTR_SIZE(z)      ((z)->size & ~ZSTR_STATIC_FLAG)
#define ZSTR_IS_STATIC(z) ((z)->size & ZSTR_STATIC_FLAG)

#define ZSTR_STATIC(name, str) \
    static struct { uint64_t size; char data[sizeof(str)]; } \
    name##_storage = { (sizeof(str)-1) | ZSTR_STATIC_FLAG, str }; \
    static ZStr* name = (ZStr*)&name##_storage

static ZStr* zstr_new(const char* s) {
    uint64_t size = (uint64_t)strlen(s);
    ZStr* z = (ZStr*)malloc(sizeof(ZStr) + size + 1);
    z->size = size;
    memcpy(z->data, s, size + 1);
    return z;
}

static ZStr* zstr_cat(ZStr* a, ZStr* b) {
    uint64_t size = ZSTR_SIZE(a) + ZSTR_SIZE(b);
    ZStr* z = (ZStr*)malloc(sizeof(ZStr) + size + 1);
    z->size = size;
    memcpy(z->data, a->data, ZSTR_SIZE(a));
    memcpy(z->data + ZSTR_SIZE(a), b->data, ZSTR_SIZE(b) + 1);
    return z;
}

static ZStr* zstr_from_i64(int64_t n) {
    char buf[32];
    snprintf(buf, sizeof(buf), "%ld", (long)n);
    return zstr_new(buf);
}

static ZStr* zstr_from_f64(double n) {
    char buf[64];
    snprintf(buf, sizeof(buf), "%g", n);
    return zstr_new(buf);
}

static void zstr_print(ZStr* s) {
    printf("%.*s\n", (int)ZSTR_SIZE(s), s->data);
}

static void zstr_free(ZStr* s) {
    if (s && !ZSTR_IS_STATIC(s)) free(s);
}

ZSTR_STATIC(_zs1, "ok");
ZSTR_STATIC(_zs2, "error");
ZSTR_STATIC(_zs3, "none");
ZSTR_STATIC(_zs4, "something went wrong");
ZSTR_STATIC(_zs5, "a is ");
ZSTR_STATIC(_zs6, "b is ");
ZSTR_STATIC(_zs7, "c is ");
ZSTR_STATIC(_zs8, "d is ");

typedef enum {
    Z_RESULT_TAG_OK,
    Z_RESULT_TAG_ERR,
    Z_RESULT_TAG_NONE,
} z_result_tag_t;

typedef struct {
    z_result_tag_t tag;
    void* data;
} z_result_t;

static void z_result_destroy(z_result_t* u) {
    if (!u) return;
    switch (u->tag) {
        case Z_RESULT_TAG_OK:
            free(u->data);
            break;
        case Z_RESULT_TAG_ERR:
            zstr_free((ZStr*)u->data);
            break;
        case Z_RESULT_TAG_NONE:
            break;
    }
    free(u);
}

typedef enum {
    Z_TYPED_TAG_U8,
    Z_TYPED_TAG_U16,
    Z_TYPED_TAG_U32,
} z_typed_tag_t;

typedef struct {
    z_typed_tag_t tag;
    void* data;
} z_typed_t;

static void z_typed_destroy(z_typed_t* u) {
    if (!u) return;
    switch (u->tag) {
        case Z_TYPED_TAG_U8:
            free(u->data);
            break;
        case Z_TYPED_TAG_U16:
            free(u->data);
            break;
        case Z_TYPED_TAG_U32:
            free(u->data);
            break;
    }
    free(u);
}

ZStr* z_describe(z_result_t* r);
void z_main(void);

ZStr* z_describe(z_result_t* r) {
    switch (r->tag) {
        case Z_RESULT_TAG_OK: {
            return _zs1;
            break;
        }
        case Z_RESULT_TAG_ERR: {
            return _zs2;
            break;
        }
        case Z_RESULT_TAG_NONE: {
            return _zs3;
            break;
        }
    }
}

void z_main(void) {
    z_result_t* _c1 = (z_result_t*)malloc(sizeof(z_result_t));
    _c1->tag = Z_RESULT_TAG_OK;
    int64_t* _box2 = (int64_t*)malloc(sizeof(int64_t));
    *_box2 = 42;
    _c1->data = _box2;
    z_result_t* a = _c1;
    z_result_t* _c3 = (z_result_t*)malloc(sizeof(z_result_t));
    _c3->tag = Z_RESULT_TAG_ERR;
    _c3->data = _zs4;
    z_result_t* b = _c3;
    z_result_t* _c4 = (z_result_t*)malloc(sizeof(z_result_t));
    _c4->tag = Z_RESULT_TAG_NONE;
    _c4->data = NULL;
    z_result_t* c = _c4;
    ZStr* _t5 = z_describe(a);
    ZStr* _t6 = zstr_cat(_zs5, _t5);
    zstr_print(_t6);
    zstr_free(_t5);
    zstr_free(_t6);
    ZStr* _t7 = z_describe(b);
    ZStr* _t8 = zstr_cat(_zs6, _t7);
    zstr_print(_t8);
    zstr_free(_t7);
    zstr_free(_t8);
    ZStr* _t9 = z_describe(c);
    ZStr* _t10 = zstr_cat(_zs7, _t9);
    zstr_print(_t10);
    zstr_free(_t9);
    zstr_free(_t10);
    z_result_t* d = a;
    a = NULL;
    ZStr* _t11 = z_describe(d);
    ZStr* _t12 = zstr_cat(_zs8, _t11);
    zstr_print(_t12);
    zstr_free(_t11);
    zstr_free(_t12);
    z_typed_t* _c13 = (z_typed_t*)malloc(sizeof(z_typed_t));
    _c13->tag = Z_TYPED_TAG_U8;
    uint8_t* _box14 = (uint8_t*)malloc(sizeof(uint8_t));
    *_box14 = 1;
    _c13->data = _box14;
    z_typed_t* t = _c13;
    zstr_print(_zs1);
    z_typed_destroy(t);
    z_result_destroy(d);
    z_result_destroy(c);
    z_result_destroy(b);
    z_result_destroy(a);
}

int main(int argc, char* argv[]) {
    z_main();
    return 0;
}
